name: Workflow
on: workflow_dispatch
jobs:
  release:
    name: Release
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Dependencies
        run: sudo apt update && sudo apt install libboost-system-dev
      - name: Configure
        run: cmake -B build -D CMAKE_BUILD_TYPE=Release
      - name: Build
        run: cmake --build build --parallel
      - name: Pack
        run: cpack -G "ZIP;DEB;RPM" -B packages --config build/CPackConfig.cmake
      - name: Install
        run: sudo dpkg -i packages/*.deb
      - name: Release
        uses: actions/create-release@v1
        id: create-release
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          body: Release packages
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: packages/practice-0.1-linux.zip
          asset_name: practice-0.1-linux.zip
          asset_content_type: application/zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
